### ISSUE TITLE
is my camera able to handle docker?

### ISSUE THREAD

**Issue by stephanschulz** [antimodular/axis-camera-computervision#3]
The readme says:
> Go in System -> Plain config -> search -> "Docker" disable TLS,

But I do not see the word Docker?
![Screen Shot 2022-04-13 at 8 23 54 PM](https://user-images.githubusercontent.com/1054816/163290543-7cea1ebd-704b-43f2-a773-527dd45b54b4.jpg)

**Comment by stephanschulz** [comment]
I tried anyway to install on to the camera via 
`docker run --rm axisecp/docker-acap:latest-armv7hf 198.168.0.10 myPassword install`

and got this message:
![Screen Shot 2022-04-14 at 7 46 43 AM](https://user-images.githubusercontent.com/1054816/163384524-7179ed1d-fb7d-49ce-afe8-20edbb21bc2e.jpg)

**Comment by Corallo** [comment]
Mh, I don't think there's a workaround for this, if it says that it is not supported it means that the OS of the camera is too old to host docker. 
The only possible solutions are either to get a model that supports the acap-computer-vision-sdk or to not use docker, and deploy the application as an eap file. This means however that the app has to be written in C++ instead, as python is not supported.

**Comment by stephanschulz** [comment]
I have the P3245-LVE coming in too and will try the docker stuff then.
I also hope to find P3255-LVE or P3265-LVE so i can also try some of the deep learning stuff.

I am a big fan of C++. Are there tutorials on how to do that? I am worried that this might become too much work though.

**Comment by Corallo** [comment]
Looks like the P3245-LVE is also not compatible with docker, P3255-LVE and P3265-LVE should be.

Yes, there are some examples, the complexity of creating the application for the camera once you have the app written in C++ is fairly low.

You still need to use docker, but only locally in your machine.
Here there is an example that is very similar to what you need:
https://github.com/AxisCommunications/acap-native-sdk-examples/blob/master/using-opencv/app/example.cpp#L60
Once implemented, the instruction to build and deploy the app on the camera are just 3 docker commands, they are documented in the Readme:
https://github.com/AxisCommunications/acap-native-sdk-examples/blob/master/using-opencv/README.md

**Comment by stephanschulz** [comment]
To test the opencv C++ example I followed the steps as described here: https://github.com/AxisCommunications/acap-native-sdk-examples/blob/master/using-opencv/README.md

The results from step 1.
![Screen Shot 2022-04-14 at 9 28 24 AM](https://user-images.githubusercontent.com/1054816/163402559-3896fdf1-2f5a-47f8-994a-c139bf956051.jpg)

Step 2 with the build f
![Screen Shot 2022-04-14 at 9 37 58 AM](https://user-images.githubusercontent.com/1054816/163403164-f0088349-6573-41bb-b1fd-5234c4237de8.jpg)

I am trying to upload the `.eap` file via the web interface by selecting the + sign.
![Screen Shot 2022-04-14 at 9 42 22 AM](https://user-images.githubusercontent.com/1054816/163403303-af49286d-ba05-4e94-920f-dbe0da23c412.jpg)

But i get this error message:
![Screen Shot 2022-04-14 at 9 36 34 AM](https://user-images.githubusercontent.com/1054816/163403439-4c69fb41-945b-4a1c-ba2a-3946ff7defbd.jpg)

**Comment by Corallo** [comment]
This is very strange, I tried to do the same and the app got installed properly. I don't think that the problem is proxy related.
It's either that your camera has some settings activated that block unofficial apps, or that you don't have enough space on the device and it is printing the wrong error message.

I would the following:
scp the eap file into the camera in the /tmp folder,
ssh into the camera and install the app with acapctl install /tmp/_filename_ 
and see the output of it, if it fails you can run
journalctl -u acapmanager to get more information about the error

**Comment by stephanschulz** [comment]
`scp` worked well. As you can see `ls` lists the open-cv file.

But `acapctl install /tmp/_filename_` failed because `-sh: acapctl: not found` 
![Screen Shot 2022-04-19 at 11 18 29 AM](https://user-images.githubusercontent.com/1054816/164038229-e6f86761-e0f2-482c-a07f-99d6b987639a.jpg)

I also tried `journalctl -u acapmanager` which seems to look ok.
![Screen Shot 2022-04-19 at 11 20 44 AM](https://user-images.githubusercontent.com/1054816/164038626-2dd88717-e786-4486-ae65-3c1af7023921.jpg)

**Comment by Corallo** [comment]
Could you check the firmware version? You can find it in the gui in the maintenance section

**Comment by stephanschulz** [comment]
Current firmware: 9.80.3.2

**Comment by Corallo** [comment]
It should work just out of the box, one last thing that you could try is to upgrade the firmware:
https://www.axis.com/support/firmware
you can search here for M3115 and download the 10.10.69 firmware. 
Then in the maintenance section of the camera you can do a firmware upgrade, hopefully this might also help to reset some weird settings that prevent the camera to install the ACAP.
If after doing it you still can't install the acap, unfortunately I don't know what to try next, and I would recommend opening a ticket here:
https://github.com/AxisCommunications/acap-native-sdk-examples/issues
mentioning:
- camera model
- firmware tried (both of them) 
- the screenshot of the error and the acapctl log possibly.

If you open an issue, it would be better not to mention there that we are having a direct contact.

**Comment by stephanschulz** [comment]
Upgrading the firmware did the trick.
I am now able to upload a `.eap` app via the browser interface.
![Screen Shot 2022-04-20 at 9 05 31 AM](https://user-images.githubusercontent.com/1054816/164237039-c36e622f-2b38-484f-887a-76c1091d212a.jpg)

And i am able to see print outs in the browser `App log` window:
![Screen Shot 2022-04-20 at 9 06 09 AM](https://user-images.githubusercontent.com/1054816/164237223-5e26d69a-ee50-4d15-9497-9bf6f6667f71.jpg)

And i able to ssh in to the camera and use `journalctl -f` to see a continuous printout.
